Python 2.7 Titan:
  script:
  - py_version=2.7
  - EXTRA_INSTALL="numpy mako"
  - echo "CUDADRV_LIB_DIR = ['/usr/lib/x86_64-linux-gnu/nvidia/current']" > siteconf.py
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - nvidia-titan-black
  except:
  - tags
Python 2.7 K40:
  script:
  - py_version=2.7
  - EXTRA_INSTALL="numpy mako"
  - echo "CUDADRV_LIB_DIR = ['/usr/lib/x86_64-linux-gnu/nvidia/current']" > siteconf.py
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - nvidia-k40
  except:
  - tags
Python 3.4 Titan:
  script:
  - py_version=3.4
  - EXTRA_INSTALL="numpy mako"
  - echo "CUDADRV_LIB_DIR = ['/usr/lib/x86_64-linux-gnu/nvidia/current']" > siteconf.py
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.4
  - nvidia-titan-black
  except:
  - tags
